# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJfcbktsB5Qa6tSjhVGl2S351qkENV7l
"""

age=12
name="Satish"
print("The age is:",age,"name is",name)